"""add index on compliance_event due_date

Revision ID: d0524dd3af66
Revises: d6d631337157
Create Date: 2026-07-13 14:54:40.160510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0524dd3af66'
down_revision = 'd6d631337157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_event_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_event_due_date'))

    # ### end Alembic commands ###
