"""add created_at to compliance_event

Revision ID: d6d631337157
Revises: ee478aeaa67e
Create Date: 2026-07-08 07:38:38.846102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d631337157'
down_revision = 'ee478aeaa67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_event', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
