"""add whatsapp_message table

Revision ID: dee7fc1219a2
Revises: d0524dd3af66
Create Date: 2026-07-14 07:13:02.339582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee7fc1219a2'
down_revision = 'd0524dd3af66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('compliance_event_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=10), nullable=False),
    sa.Column('to_phone_masked', sa.String(length=20), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('body_preview', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('twilio_sid', sa.String(length=50), nullable=True),
    sa.Column('error_detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compliance_event_id'], ['compliance_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_message_compliance_event_id'), ['compliance_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_message_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_compliance_event_id'))

    op.drop_table('whatsapp_message')
    # ### end Alembic commands ###
