"""add legislation table

Revision ID: e27e4ffd7f99
Revises: b7f3a1d9c2e8
Create Date: 2026-06-14 17:28:07.089843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27e4ffd7f99'
down_revision = 'b7f3a1d9c2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('summary_hi', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('last_verified_on', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legislation')
    # ### end Alembic commands ###
