"""add news_item and news_document tables

Revision ID: ee478aeaa67e
Revises: e27e4ffd7f99
Create Date: 2026-06-17 16:39:06.689758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee478aeaa67e'
down_revision = 'e27e4ffd7f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_item_dedup_hash'), ['dedup_hash'], unique=True)
        batch_op.create_index('ix_news_item_order_date', ['order_date'], unique=False)

    op.create_table('news_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'url', name='uq_news_document_item_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_document')
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.drop_index('ix_news_item_order_date')
        batch_op.drop_index(batch_op.f('ix_news_item_dedup_hash'))

    op.drop_table('news_item')
    # ### end Alembic commands ###
